services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: zionwebix/client22
    container_name: vote-client
    ports:
      - "8080:80"
    networks:
      - vote-network 
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: zionwebix/server22
    container_name: vote-server
    ports:
      - "3031:3030"
    networks:
      - vote-network 
    depends_on:
      - mongo-db
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}

  mongo-db:
    image: mongo
    container_name: vote-mongo-db
    ports:
      - "3032:27017"
    networks:
      - vote-network
    restart:
      always
    volumes:
      - vote-volume:/data/db

networks:
  vote-network:
    driver: bridge

volumes:
  vote-volume:
  