services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vote-client
    ports:
      - "8080:80"
    networks:
      - vote-network 
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vote-server
    ports:
      - "3030:3000"
    networks:
      - vote-network 
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: vote-mongo-db
    ports:
      - "3031:27017"
    networks:
      - vote-network
    restart:
      always
    volumes:
      - vote-volume:/data/db

networks:
  vote-network:
    driver: bridge

volumes:
  vote-volume:
  